import { BookOpen, ChevronRight, Flame, Users } from "lucide-react"
import Link from "next/link"

type FeedSidebarProps = { isVietnamese: boolean }

export function FeedSidebar({ isVietnamese }: FeedSidebarProps) {
  return <aside className="space-y-5 lg:sticky lg:top-24 lg:self-start">
    <section className="rounded-2xl bg-[#17352d] p-5 text-white"><div className="flex items-center gap-2 text-[#f3d7a3]"><Flame className="size-4" /><span className="text-xs font-bold uppercase tracking-[0.14em]">{isVietnamese ? "Bếp nổi bật" : "Kitchen spotlight"}</span></div><h2 className="mt-4 font-serif text-2xl leading-tight">{isVietnamese ? "Nấu chậm, chia sẻ nhiều hơn." : "Cook slowly. Share generously."}</h2><p className="mt-3 text-sm leading-6 text-white/65">{isVietnamese ? "Một cộng đồng nhỏ cho những món ăn có câu chuyện." : "A small community for food with a story behind it."}</p><Link href="/playground" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#f3d7a3]">{isVietnamese ? "Vào bếp rảnh tay" : "Open the kitchen"}<ChevronRight className="size-4" /></Link></section>
    <section className="rounded-2xl border border-[#dbe5dd] bg-white p-5"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-[#fff1df] text-[#d97742]"><Users className="size-4" /></span><div><h2 className="text-sm font-bold">{isVietnamese ? "Những đầu bếp bạn có thể thích" : "Cooks to follow"}</h2><p className="text-xs text-[#789087]">{isVietnamese ? "Mới trong cộng đồng" : "Fresh in the community"}</p></div></div><div className="mt-5 space-y-4">{[["Nora Kim", "NK", "Fermentation fan"], ["Bao Nguyen", "BN", "One-pan meals"], ["Elena Rossi", "ER", "Sunday baker"]].map(([name, initials, role]) => <div key={name} className="flex items-center gap-3"><div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-[#a9c2a5] text-[10px] font-bold text-[#17352d]">{initials}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{name}</p><p className="truncate text-xs text-[#789087]">{role}</p></div><button type="button" className="shrink-0 rounded-full border border-[#c5d2cc] px-2.5 py-1 text-xs font-bold text-[#527066] hover:border-[#d97742] hover:text-[#d97742]">{isVietnamese ? "Theo dõi" : "Follow"}</button></div>)}</div></section>
    <section className="rounded-2xl border border-[#dbe5dd] bg-[#f1f5ef] p-5"><div className="flex items-center gap-2 text-[#d97742]"><BookOpen className="size-4" /><h2 className="text-sm font-bold">{isVietnamese ? "Chủ đề đang được yêu thích" : "Trending topics"}</h2></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#527066]">#comfortfood</span><span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#527066]">#mealprep</span><span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#527066]">#baking</span></div></section>
  </aside>
}